%% INPUT FILE FOR RUNNING Anyway ICA FUSION %%
% After entering the parameters, call batch script using ica_fuse_anyway_fusion_batch(inputFile); at the MATLAB command prompt.
% The input parameters are defined below. Please use full path for files or directory
% Reference.txt file below is created with dummy weights and needed for reference
% Input data is found at:
%   https://trends-public-website-fileshare.s3.amazonaws.com/public_website_files/software/fit/data/Fusion_Example_Data.zip
%      Under Example Subjects
%      https://github.com/trendscenter/fit 
%   Input data may be placed under /home/my/Fusion_Example_Data

%% Output directory
outputDir = '/home/my/out/result';

%% Output files prefix
% Specify a value that generates a valid variable name.
% Output prefix must not contain Empty space, \, /, ?, :, *, ", <, > or any
% other character that doesn't generate a valid variable name.
prefix = 'fmrieeg';

%% Mask file
% 1. Default mask - Specify empty value like [].
%
% 2. When specifying maskFiles enter in a cell array. For each feature there
% is a mask.
% fMRI - full file path
% Gene - indices like '1:367'
% sMRI - full file path
%
% NOTE:
% To replicate the same mask over features you can use repmat for example
% maskFile = repmat({'/home/my/mask.img'}, 2, 1);
maskFile = [];

%% Feature names 
% Enter feature names in a cell array of length 2
featureNames = {'fMRI', 'EEG'};

%% Modality selection.
% This will be a vector of length equal to 2.
% Please see variable PARALLEL_ICA_MODALITIES in ica_fuse_defaults.m for available
% modalities.
modality = {'fmri', 'eeg'};

%% Input files is a cell array of length number of features. Each cell
% contains a character array of file names.
sDirSubs='/home/my/Fusion_Example_Data/Fusion_Data/erp_fmri';

% two groups into sFilFmri
sFilFmri = {[sDirSubs '/s1103/fMRI_stats/beta.img'], ...
            [sDirSubs '/s162/fMRI_stats/beta.img'], ...
            [sDirSubs '/s164/fMRI_stats/beta.img'], ...
            [sDirSubs '/s196/fMRI_stats/beta.img'], ...
            [sDirSubs '/s199/fMRI_stats/beta.img'], ...
            [sDirSubs '/s210/fMRI_stats/beta.img'], ...
            [sDirSubs '/s233/fMRI_stats/beta.img'], ...
            [sDirSubs '/s245/fMRI_stats/beta.img'], ...
            [sDirSubs '/s247/fMRI_stats/beta.img'], ...
            [sDirSubs '/s282/fMRI_stats/beta.img'], ...
            [sDirSubs '/s308/fMRI_stats/beta.img']; ...
            ...
            [sDirSubs '/s332/fMRI_stats/beta.img'], ...
            [sDirSubs '/s374/fMRI_stats/beta.img'], ...
            [sDirSubs '/s406/fMRI_stats/beta.img'], ...
            [sDirSubs '/s476/fMRI_stats/beta.img'], ...
            [sDirSubs '/s573/fMRI_stats/beta.img'], ...
            [sDirSubs '/s628/fMRI_stats/beta.img'], ...
            [sDirSubs '/s643/fMRI_stats/beta.img'], ...
            [sDirSubs '/s661/fMRI_stats/beta.img'], ...
            [sDirSubs '/s677/fMRI_stats/beta.img'], ...
            [sDirSubs '/s695/fMRI_stats/beta.img'], ...
            [sDirSubs '/s697/fMRI_stats/beta.img']};

% two groups into sFilErp
sFilErp = {[sDirSubs '/s1103/ERP_asc/fnaod_s382_ica-b12-c30.asc'], ...
            [sDirSubs '/s162/ERP_asc/fnaod_s155_ica-b12-c30.asc'], ...
            [sDirSubs '/s164/ERP_asc/fnaod_s282_ica-b12-c30.asc'], ...
            [sDirSubs '/s196/ERP_asc/fnaod_s187_ica-b12-c30.asc'], ...
            [sDirSubs '/s199/ERP_asc/fnaod_s158_ica-b12-c30.asc'], ...
            [sDirSubs '/s210/ERP_asc/fnaod_s159_ica-b12-c30.asc'], ...
            [sDirSubs '/s233/ERP_asc/fnaod_s168_ica-b12-c30.asc'], ...
            [sDirSubs '/s245/ERP_asc/fnaod_s165_ica-b12-c30.asc'], ...
            [sDirSubs '/s247/ERP_asc/fnaod_s203_ica-b12-c30.asc'], ...
            [sDirSubs '/s282/ERP_asc/fnaod_s188_ica-b12-c30.asc'], ...
            [sDirSubs '/s308/ERP_asc/fnaod_s327_ica-b12-c30.asc']; ...
            ...
            [sDirSubs '/s332/ERP_asc/fnaod_s366_ica-b12-c30.asc'], ...
            [sDirSubs '/s374/ERP_asc/fnaod_s183_ica-b12-c30.asc'], ...
            [sDirSubs '/s406/ERP_asc/fnaod_s206_ica-b12-c30.asc'], ...
            [sDirSubs '/s476/ERP_asc/fnaod_s229_ica-b12-c30.asc'], ...
            [sDirSubs '/s573/ERP_asc/fnaod_s194_ica-b12-c30.asc'], ...
            [sDirSubs '/s628/ERP_asc/fnaod_s359_ica-b12-c30.asc'], ...
            [sDirSubs '/s643/ERP_asc/fnaod_s350_ica-b12-c30.asc'], ...
            [sDirSubs '/s661/ERP_asc/fnaod_s352_ica-b12-c30.asc'], ...
            [sDirSubs '/s677/ERP_asc/fnaod_s307_ica-b12-c30.asc'], ...
            [sDirSubs '/s695/ERP_asc/fnaod_s376_ica-b12-c30.asc'], ...
            [sDirSubs '/s697/ERP_asc/fnaod_s342_ica-b12-c30.asc']};

files = {sFilFmri;sFilErp};

%% Number of components. Length of the vector is equal to the number of features.
numComp = [8,8];

%% Scale components to z-scores. Options are 'none' and 'z-scores'
scale_components = 'z-scores';

%% Algorithm options
algorithm_opts.lambda_iva = 0.19;

%% Reference file name for running anyway fusion analysis with reference
% Text file should contain vector equal to the number of subjects in the
% analysis. If running standard anyway fusion, leave it as empty

%Line below created a file with 22 dummy weights just for the demo data
writematrix([25 64 53 64 15 42 32 21 34 42 31 24 28 38 29 27 19 27 29 16 42 22]', '/home/my/reference.txt');

%Information wehere your reference file is
reference_ica = '/home/my/reference.txt';

%% display
display_results.format = 'html';
display_results.image_values = 'positive and negative';
display_results.anatomical_plane = 'axial';
display_results.slices_in_mm = -40:4:72;
display_results.convert_to_z = 'yes';
display_results.threshold = 1.5;